# Generated by Django 5.2.4 on 2025-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='pokemon_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generation', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pokemon', models.ManyToManyField(related_name='teams', to='teams.pokemon')),
            ],
        ),
    ]
