# Generated by Django 5.2.4 on 2025-07-12 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='teams.team'),
        ),
    ]
