# Generated by Django 5.2.4 on 2025-07-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_pokemon_pokemon_species_pokemon_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image',
        ),
    ]
