# Generated by Django 5.2.4 on 2025-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
