# Generated by Django 5.2.4 on 2025-07-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
