# Generated by Django 5.2.4 on 2025-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='apiId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
